server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./.h2/shop;AUTO_SERVER=true;INIT=CREATE SCHEMA IF NOT EXISTS shopping;
    username: admin
    password: root
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect